kind: pipeline
name: build

concurrency:
  limit: 1

steps:
  - name: build
    image: python:alpine
    commands:
      - pip wheel .
      - rm -r pcsd.egg-info/ build/
      - mkdir package
      - mv *.whl package
  - name: publish
    image: pwddocker/drone-publish:latest
    environment:
      PASS:
        from_secret: pass
      USER:
        from_secret: user
    commands:
      - python3 -m twine upload --repository-url https://git.glebmail.xyz/api/packages/PythonPrograms/pypi -u $USER -p $PASS package/*.whl

trigger:
   event: [ tag, push ]
   branch: [ master ]

kind: pipeline
type: docker
name: test

concurrency:
  limit: 1

steps:
  - name: test
    image: python
    commands:
      - pip install .
      - pcsd test

trigger:
   event: [ pull_request, push ]